name: CI trigger

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  run-CI-workflow:
    runs-on: ubuntu-latest
    name: run CI workflow
    steps:
      - name: run
        run: echo "this is a dummy workflow that triggers a workflow_run; it's necessary because otherwise the repo secrets will not be in scope for externally forked pull requests"
