name: CI triggered by PR

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["CI trigger"]
    types: [completed]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set environment variables
        run: |
          cd ./src/test/resources
          echo "${{ secrets.ENV }}" > ./application-secret.properties

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: test
        run: |
          chmod +x gradlew 
          ./gradlew test
